services:
  db:
    container_name: pg_cont
    image: postgres:15
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - my_network

  python:
    build: .
    container_name: python_cont
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./scripts:/usr/src/app/scripts
      - ./data:/usr/scr/app/data
    working_dir: /usr/src/app
    command: python scripts/run_pipeline.py
    networks:
      - my_network

  dbt:
    container_name: dbt_cont
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/my_project:/usr/app/
      - ./dbt:/root/.dbt
    working_dir: /usr/app/my_project
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - db
      - python
    networks:
      - my_network
    command: ["run"]

  metabase:
    container_name: metabase_cont
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=db_user
      - MB_DB_PASS=postgres
      - MB_DB_HOST=db
    depends_on:
      - db
    networks:
      - my_network


networks:
  my_network:
    driver: bridge